# Generated by Django 4.1.7 on 2023-02-22 17:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('nick', models.CharField(max_length=30)),
                ('rank', models.FloatField()),
                ('is_active', models.BooleanField(default=False)),
                ('is_online', models.BooleanField(default=False)),
                ('is_bot', models.BooleanField(default=False)),
                ('isSearchVisible', models.BooleanField(default=False)),
                ('isRankVisible', models.BooleanField(default=False)),
                ('theme', models.BooleanField(default=False)),
            ],
        ),
    ]
