# Generated by Django 4.1.7 on 2023-02-20 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=30)),
                ('rank', models.PositiveSmallIntegerField()),
                ('is_bot', models.BooleanField(default=False)),
            ],
        ),
    ]
