# Generated by Django 4.1.7 on 2023-02-20 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='rank',
            field=models.FloatField(),
        ),
    ]
