# Generated by Django 4.1.7 on 2023-02-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_player_is_active_player_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='isRankVisible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='isSearchVisible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='theme',
            field=models.BooleanField(default=False),
        ),
    ]
