# Generated by Django 4.1.7 on 2023-02-22 13:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_player_isrankvisible_player_issearchvisible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
