services:
  backend_dev_me_up:
    build:
      context: ./backend_core
    volumes:
      - ./backend_core:/app
    env_file:
      - ./backend_core/envs/.env_django
      - ./backend_core/envs/.env_db
    ports:
      - 8000:8000
    restart: on-failure

    networks:
      - backend_db_network
      - redis_network
    depends_on:
      - backend_db

  redis:
    image: 'redis:6-alpine'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - redis_network
    ports:
      - 6379:6379

  backend_db:
    image: postgres:15-alpine
    volumes:
      - backend_db:/var/lib/postgresql/data
    env_file:
      - ./backend_core/envs/.env_db
    ports:
      - 5432:5432
    networks:
      - backend_db_network

networks:
  backend_db_network:
  redis_network:

volumes:
    backend_db:
