# Generated by Django 4.1.7 on 2023-02-22 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('technologies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('correct_answer', models.CharField(max_length=300)),
                ('wrong_answer_1', models.CharField(max_length=300)),
                ('wrong_answer_2', models.CharField(max_length=300)),
                ('wrong_answer_3', models.CharField(max_length=300)),
                ('difficulty_level', models.PositiveIntegerField()),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s', to='technologies.technology')),
            ],
        ),
    ]
