# Generated by Django 4.1.7 on 2023-02-22 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_information', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_identity', models.CharField(max_length=50, unique=True)),
                ('creation_date', models.DateTimeField()),
                ('accounts', models.ManyToManyField(related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
                ('device_information', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s', to='applications.deviceinformation')),
                ('players', models.ManyToManyField(related_name='%(class)s', to='players.player')),
            ],
        ),
    ]
