# Generated by Django 4.1.7 on 2023-02-22 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0001_initial'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='accounts',
            field=models.ManyToManyField(related_name='%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='device_information',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s', to='applications.deviceinformation'),
        ),
        migrations.AddField(
            model_name='application',
            name='players',
            field=models.ManyToManyField(related_name='%(class)s', to='players.player'),
        ),
    ]
