# Generated by Django 4.1.7 on 2023-02-22 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quizzes', '0001_initial'),
        ('technologies', '0001_initial'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GameSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty_level', models.FloatField()),
                ('question', models.CharField(max_length=255)),
                ('correct_answer', models.CharField(max_length=255)),
                ('add_answer1', models.CharField(max_length=255)),
                ('add_answer2', models.CharField(max_length=255)),
                ('add_answer3', models.CharField(max_length=255)),
                ('source_set', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s', to='gamesets.sourceset')),
                ('technologies', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s', to='technologies.technology')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.IntegerField(blank=True, null=True)),
                ('answer_player_1', models.BooleanField(null=True)),
                ('answer_player_2', models.BooleanField(null=True)),
                ('response_bot_time', models.DateTimeField(null=True)),
                ('reponse_send', models.BooleanField(default=False, null=True)),
                ('game_sets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='gamesets.gameset')),
                ('player_id_1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='players.player')),
                ('player_id_2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='players.player')),
                ('quiz', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='quizzes.quiz')),
            ],
        ),
    ]
