# Generated by Django 4.1.7 on 2023-02-21 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_alter_player_rank'),
        ('gamesets', '0002_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='player_id_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='players.player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_id_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='players.player'),
        ),
    ]
