# Generated by Django 4.1.7 on 2023-02-21 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technologies', '0003_technologiestoplayers_technology'),
        ('gamesets', '0003_alter_game_player_id_1_alter_game_player_id_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameset',
            name='technologies',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s', to='technologies.technology'),
        ),
    ]
