# Generated by Django 4.1.7 on 2023-02-21 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
        ('gamesets', '0004_alter_gameset_technologies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='date_end',
        ),
        migrations.RemoveField(
            model_name='game',
            name='date_start',
        ),
        migrations.AddField(
            model_name='game',
            name='answer_player_1',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='answer_player_2',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='quiz',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='quizzes.quiz'),
        ),
    ]
