# Generated by Django 4.1.7 on 2023-02-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamesets', '0006_alter_game_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='reponse_send',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='response_bot_time',
            field=models.DateTimeField(default='2022-03-04 10:30'),
            preserve_default=False,
        ),
    ]
