# Generated by Django 4.1.7 on 2023-02-21 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0002_alter_player_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerRankHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_value', models.FloatField()),
                ('rank_change_date', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s', to='players.player')),
            ],
        ),
    ]
