# Generated by Django 4.1.7 on 2023-02-21 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rank_histories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerrankhistory',
            options={'verbose_name_plural': 'Player Ranks Histories'},
        ),
    ]
