# Generated by Django 4.1.7 on 2023-02-22 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Technologies',
            },
        ),
        migrations.CreateModel(
            name='TechnologiesToPlayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_rank', models.FloatField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s', to='players.player')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s', to='technologies.technology')),
            ],
        ),
    ]
