# Generated by Django 4.1.7 on 2023-02-20 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technologies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technologies',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
