# Generated by Django 4.1.7 on 2023-02-21 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technologies', '0003_technologiestoplayers_technology'),
        ('gamesets', '0004_alter_gameset_technologies'),
        ('players', '0003_player_is_active_player_is_online'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Technologies',
        ),
        migrations.AddField(
            model_name='technologiestoplayers',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s', to='players.player'),
        ),
        migrations.AddField(
            model_name='technologiestoplayers',
            name='technology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s', to='technologies.technology'),
        ),
    ]
