# Generated by Django 4.1.7 on 2023-02-21 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('infographics', '0001_initial'), ('infographics', '0002_rename_value_infographic_information')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Infographic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('information', models.CharField(max_length=255)),
            ],
        ),
    ]
