# Generated by Django 4.1.7 on 2023-02-21 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infographics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infographic',
            old_name='value',
            new_name='information',
        ),
    ]
